spring.application.name=AI_ResumeRAG_BE

server.port=8080
server.servlet.context-path = /api

# ==============================
# PostgreSQL Database
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_resume_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# JWT
# ==============================
jwt.secret=dhakjhgGJHHBhwhC=JBJhe+/kjsbfkjsgvewhgTFHGCGEv
jwt.expiration=86400000

# ==============================
# Multipart File Upload
# ==============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text

# ==============================
# Logging
# ==============================
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.SQL=DEBUG

# ==============================
# Email (Spring Mail)
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kewinmahimaidas2005@gmail.com
spring.mail.password=bkirpioditcjbrlg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Frontend URL for email links
app.frontend.url=http://localhost:3000